### ISSUE TITLE
package.json module field

### ISSUE THREAD

**Issue by phshy0607** [Donaldcwl/browser-image-compression#102]
Hi, I used this compression tool in my project. And I encountered an issue in old browsers. 

In package.json module field, the module is target to dist/browser-image-compression.mjs.
And in my webpack config, i didn't include node_modules to compile and babel-loader only targets to .js and .jsx extension, which lead mjs to browser env and caused error.

I think target module field to standard es6 build and use .js as the extension will make a lot sense. or you can clarify it in the readme?

**Comment by Donaldcwl** [comment]
@phshy0607 
Thanks for using this library.
.mjs is a standard way to explicitly define the type of file is ES module.
Webpack can recognize .mjs ES module by default, you do not need to add extra config in webpack config in order to use this library. Please find the following working example:
https://github.com/Donaldcwl/browser-image-compression/tree/bd1bb383b3b381d8a2b244372026a3b6c0bdff62/example/Webpack%20App
