### ISSUE TITLE
showing error while compressing globalThis is not defined 

### ISSUE THREAD

**Issue by modernsilpi** [Donaldcwl/browser-image-compression#108]
in some device compression not working throwing this error "globalThis is not defined "

**Comment by tianwawawa** [comment]
chrome version > 70

**Comment by tianwawawa** [comment]
check out your chrome version

**Comment by Donaldcwl** [comment]
@modernsilpi "globalThis" is widely supported by modern browsers. Please check here: https://caniuse.com/?search=globalThis

**Comment by zhicong** [comment]
I ran into this issue as well when trying to figure out why image compression was failing on old browsers. Since the package needs globalThis to work, it would be great if you could update your compatibility table to show that IE 10 and 11 are not supported.

![Screenshot 2021-07-13 at 1 15 24 AM](https://user-images.githubusercontent.com/6629493/125329233-d7703300-e377-11eb-96b2-d82ed8bfe264.png)

 Thanks for creating this package to make image compression a breeze!

**Comment by Donaldcwl** [comment]
> I ran into this issue as well when trying to figure out why image compression was failing on old browsers. Since the package needs globalThis to work, it would be great if you could update your compatibility table to show that IE 10 and 11 are not supported.
> 
> ![Screenshot 2021-07-13 at 1 15 24 AM](https://user-images.githubusercontent.com/6629493/125329233-d7703300-e377-11eb-96b2-d82ed8bfe264.png)
> 
> Thanks for creating this package to make image compression a breeze!

IE compatibility fixed in v1.0.15
