### ISSUE TITLE
The received filepath suffix disappears after compression

### ISSUE THREAD

**Issue by XAihan** [Donaldcwl/browser-image-compression#199]
After I use file compression, I pass it to the back end. The back-end received fielpath without a suffix.

I have identified the problem: the lack of a suffix caused by the canvas to blob step.
After that component is converted, the filename in the generated blob is the default blob. The filepath suffix is generated based on filename. So there's no suffix.

There are two solutions,
 one is to set the blob filename when uploading. Another option is to configure filename when generating BLOBs.

**Comment by XAihan** [comment]
https://juejin.cn/post/7145057361504403470   
The solutions I provide now are all carried out in the second operation, can I directly add this step in the compression?

**Comment by XAihan** [comment]
<img width="780" alt="image" src="https://github.com/Donaldcwl/browser-image-compression/assets/56574869/c86ff951-d87a-435b-80e4-7d84dce7c731">
i saw this. 

![image](https://github.com/Donaldcwl/browser-image-compression/assets/56574869/3a645524-faeb-4c6c-9cd7-a75752fdfba1)
And this.  It looks like edge now supports File constructor

**Comment by Donaldcwl** [comment]
@XAihan Thanks for the nicely written blog to help people who use this library in the Chinese community.

The main reason for using `new Blob` instead of `new File` is that Safari has an issue with the File constructor not being able to POST in FormData. (see https://bugs.webkit.org/show_bug.cgi?id=165081)

Therefore, I would suggest your first solution which provide the image name (e.g., a.png) when appending the blob to FormData.
```javascript
const forms = new FormData();
file = await handleCompressFile(file);
forms.append('data', file, 'a.png');
```
