### ISSUE TITLE
Wrong proportions at the output

### ISSUE THREAD

**Issue by ArthurMiroslavsky** [Donaldcwl/browser-image-compression#6]
Hi, great job! But i have a some issue with proportions. I take a portrait orientation and get the output image, which is rotated and squeezed

**Comment by Donaldcwl** [comment]
Hi,
Can you upload the image so that I can have to look at the issue?
Thanks.

**Comment by Awestin17** [comment]
Hi, I seem to be having the same or similar issue. From a file select, if a mobile user chooses to take a new picture instead of choosing one from their gallery and the photo they take is in portrait, then the resulting compressed photo has a black bar across the bottom, and the original picture is squished into a smaller area.
![DistortedPhoto](https://user-images.githubusercontent.com/17074966/55346451-84ad2e80-5480-11e9-8235-43ab836eff44.jpg)

**Comment by Donaldcwl** [comment]
@ArthurMiroslavsky @Awestin17 
The issues should be addressed in the new version v1.0.2.
Please try. Thanks!

**Comment by Awestin17** [comment]
@Donaldcwl 
Will do more testing when I get a chance but everything seems to be working as expected. Great work man!

**Comment by Donaldcwl** [comment]
@Awestin17 Thanks!
