### ISSUE TITLE
can not work on Ie 11

### ISSUE THREAD

**Issue by deathelegy** [Donaldcwl/browser-image-compression#67]

**Comment by SanjeevForYou** [comment]
I am not sure is this because, web worker option is enabled by default.
  useWebWorker: boolean,      // optional, use multi-thread web worker, fallback to run in main-thread (default: true)

If it disabled by setting useWebWorker to false, it works fine. If it is enabled i am seeing this error in console, and compress promise never resolves.
Console error :
SCRIPT0: Script Error
Line: 0

The documentation https://www.npmjs.com/package/browser-image-compression says webworker is supported in IE, but it is not working.

Note : Promise polyfill is loaded in my codebase,  https://github.com/taylorhakes/promise-polyfill

@Donaldcwl  please help !!

**Comment by Donaldcwl** [comment]
Promise API is being used in this library. If you need to support browsers that do not support Promise like IE. You can include the Promise polyfill in your project.

see more: https://github.com/Donaldcwl/browser-image-compression#ie-support
