### ISSUE TITLE
Always return Blob object

### ISSUE THREAD

**Issue by desaikalpesh34** [Donaldcwl/browser-image-compression#77]
How to return File object.
```
file = await imageCompression(file, imageOptions);
console.log(file instanceof File);//always false
```
i need this file as File Object

**Comment by edsonfeimberg** [comment]
Same here. imageCompression is always returning a blob

**Comment by jiangyijie27** [comment]
@desaikalpesh34 @edsonfeimberg 

If you want a File from a Blob, can simply do this:

```js
const compressedFile = await imageCompression(file, options)
const newFile = new File([compressedFile], "compressed.png")
```

**Comment by Donaldcwl** [comment]
For better browser compatibility, I decided to use Blob instead of File.
e.g. Safari has an issue with File constructor not being able to POST in FormData
e.g. Edge (Original) does not support File constructor
see more in:
https://github.com/Donaldcwl/browser-image-compression/blob/master/lib/utils.js#L55

If you really need a File object for some reason, you can see the suggestion from @jiangyijie27.
