### ISSUE TITLE
It's seems not work in iPhone6s.

### ISSUE THREAD

**Issue by amourfrei** [Donaldcwl/browser-image-compression#8]
It's seems not work in iPhone6s.

**Comment by amourfrei** [comment]
@Donaldcwl  That seems type  'File' not work with formData in ios11.2, Use Blob works fine for me.

**Comment by Donaldcwl** [comment]
@amourfrei I used a try-catch block to use "File" and fall back to "Blob" here:
https://github.com/Donaldcwl/browser-image-compression/blob/master/lib/utils.js#L36

Are you referring to this code?

**Comment by amourfrei** [comment]
> @amourfrei I used a try-catch block to use "File" and fall back to "Blob" here:
> https://github.com/Donaldcwl/browser-image-compression/blob/master/lib/utils.js#L36
> 
> Are you referring to this code?

@Donaldcwl  Yes, in ios11.2, File can be used, but that will be empty when i append it to FormData. But it works good if use Blob.

**Comment by Donaldcwl** [comment]
> > @amourfrei I used a try-catch block to use "File" and fall back to "Blob" here:
> > https://github.com/Donaldcwl/browser-image-compression/blob/master/lib/utils.js#L36
> > Are you referring to this code?
> 
> @Donaldcwl Yes, in ios11.2, File can be used, but that will be empty when i append it to FormData. But it works good if use Blob.

@amourfrei According to the Can I Use website, https://caniuse.com/#search=File, File should be fully implemented in iOS Safari.
 What do you mean by "empty when I append it to FormData"?

**Comment by samcoenen** [comment]
Although `File` is fully supported in Safari, trying to _upload_ a **user-generated** `File` will not work, the `File` will not be attached to the upload request. A user-generated `File` has to be converted to a `Blob` before you can upload it. This has nothing to do with this library though since it's not related to the compression part, it's simply a known bug inside Safari with a user-generated `File`.

See:
https://github.com/jaydenseric/apollo-upload-client/issues/54
https://bugs.webkit.org/show_bug.cgi?id=165081

@amourfrei Convert the `File` that this library returns to a `Blob` before uploading it. This is required for every Safari browser (so not only iPhones, also iPads, MacBooks etc).

**Comment by Donaldcwl** [comment]
@samcoenen Thanks for referencing to a known bug in Safari

For the convenient use of this library, in the next release, I will bypass the issues by using only "Blob" even though "File" is supported in some browser.

To be more specific:
```js
const file = new File([u8arr], filename, { type: mime })
```
change to 
```js
const file = new Blob([u8arr], { type: mime })
file.name = filename
file.lastModified = lastModified
```
